services:

  backend:
    build:
      context: ./backend
    container_name: search-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - EMBEDDING_MODEL=nomic-embed-text
      - LLM_MODEL=qwen2.5:3b
    restart: unless-stopped
    depends_on:
      - qdrant
      - ollama
    networks:
      - search-net

  frontend:
    build:
      context: ./frontend
    container_name: search-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - search-net

  ollama:
    image: ollama/ollama:latest
    container_name: search-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - search-net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: search-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped
    networks:
      - search-net

networks:
  search-net:
    driver: bridge

volumes:
  ollama-data:
  qdrant-data: